implement silent mode
astuff/kvaser_interface pull request #87
Opened 2022-05-31 14:24 UTC by Roosta078

Implemented setting the output control mode to Silent for situations that require it.  Uses a setter method to set a flag that defaults to false.  Calls to open method are unaffected.  To use, call set_silent_mode(true) before calling open.

2022-06-06 13:19 UTC, Roosta078 commented
@icolwell-as Could you take a look at this?

2022-06-06 19:09 UTC, icolwell-as requested changes
Thanks for submitting this! Just one small thing to change.

2022-06-06 19:09 UTC, icolwell-as commented on include/kvaser_interface/kvaser_interface.h
> +  void set_silent_mode(bool _silent_mode);
The rest of the functions defined here use lower camel case, could you rename the function to `setSilentMode` for consistency?

2022-06-07 13:21 UTC, Roosta078 commented on include/kvaser_interface/kvaser_interface.h
> +  void set_silent_mode(bool _silent_mode);
Done

2022-06-07 14:39 UTC, icolwell-as approved these changes

2022-06-07 15:23 UTC, dvangeyn-as approved these changes

2022-06-07 15:33 UTC, merged